import { ArrowLeft, ArrowRight, Check, CheckCircle2, Clock3, Download, Edit3, FileCheck2, FileText, Info, LockKeyhole, Moon, Plus, Printer, Search, ShieldCheck, Sun, UserRound, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { AppShell, PortalHeader } from '../components/AppShell'
import { PortraitAvatar } from '../components/Avatar'
import { Stepper } from '../components/Stepper'
import { doctor, patient } from '../data/demo'
import { useAppState } from '../state/useAppState'

const medicines = [
  { name:'Metformin', dose:'500 mg', instruction:'Twice daily', status:'Active', tone:'blue' },
  { name:'Amlodipine', dose:'5 mg', instruction:'Once daily', status:'Needs review', tone:'coral' },
  { name:'Atorvastatin', dose:'10 mg', instruction:'Nightly', status:'Active', tone:'mint' },
  { name:'Cetirizine', dose:'10 mg', instruction:'Stopped 1 Mar 2025', status:'Historical', tone:'grey' },
  { name:'Ibuprofen', dose:'400 mg', instruction:'As needed · unclear', status:'Clarify', tone:'amber' },
]

export function VerificationPage() {
  const navigate=useNavigate(); const {setVerified}=useAppState(); const [progress,setProgress]=useState(0)
  useEffect(()=>{const timer=window.setInterval(()=>setProgress(value=>value>=4?4:value+1),700);return()=>clearInterval(timer)},[])
  const steps=['Read document','Match demo registry','Compare profile','Verified in demo mode']
  return <div className="verification-page"><header className="app-header"><Link to="/" className="brand"><span className="brand-name compact">MedPal</span><span className="brand-tagline">Care, in context.</span></Link><span>Doctor onboarding</span><div className="initial-badge">AM</div></header><main className="verification-wrap"><div className="verification-top"><div><p className="eyebrow">Demo verification</p><h1>Checking your credentials</h1><p>We’re comparing your profile with a synthetic demonstration registry.</p></div><Stepper steps={['Profile','Practice','Verify credentials','Complete']} current={progress===4?4:3}/></div><div className="verification-grid"><section className="paper certificate-card"><div className="certificate"><small>SYNTHETIC DEMO CERTIFICATE</small><h2>Maharashtra<br />Medical Council</h2><div className="seal"><ShieldCheck /></div><p>This demonstration record confirms</p><strong>{doctor.name}</strong><dl><div><dt>Registration</dt><dd>{doctor.registration}</dd></div><div><dt>Qualification</dt><dd>{doctor.qualification}</dd></div></dl></div><div className="extracted"><p className="eyebrow ink">Extracted details</p><h2>Profile match</h2><dl><div><dt>Name</dt><dd>{doctor.name}</dd></div><div><dt>Council</dt><dd>{doctor.council}</dd></div><div><dt>Registration</dt><dd className="mono">{doctor.registration}</dd></div></dl></div></section><section className="verify-track">{steps.map((step,index)=><div className={`verify-step ${progress>index?'complete':progress===index?'active':''}`} key={step}><span>{progress>index?<Check />:index+1}</span><div><strong>{step}</strong><small>{index===0?'Reading document fields':index===1?'Checking synthetic data':index===2?'Comparing the submitted profile':'Ready for the MedPal demo'}</small></div><em>00:0{Math.min((index+1)*2,8)}</em></div>)}<div className="demo-disclosure"><Info /><span><strong>Hackathon demonstration using synthetic registry data.</strong><small>No government registry was contacted.</small></span></div><button disabled={progress<4} className="button primary wide" onClick={()=>{setVerified(true);navigate('/doctor/home')}}>Go to doctor home<ArrowRight /></button></section></div></main></div>
}

export function DoctorHomePage(){const navigate=useNavigate(); const [searched,setSearched]=useState(false);return <AppShell role="doctor"><PortalHeader eyebrow="Monday · Mehta Family Clinic" title="Good morning, Dr. Arjun."><span className="status-pill"><CheckCircle2 />Demo verified</span></PortalHeader><main className="dashboard-content"><section className="paper lookup-card"><p className="eyebrow ink">Start a consultation</p><h2>Find your patient</h2><p>Use the mobile number connected to their MedPal account.</p><div className="search-row"><span>+91</span><input defaultValue={patient.phone}/><button className="button primary" onClick={()=>setSearched(true)}><Search />Find patient</button></div>{searched&&<div className="patient-result"><PortraitAvatar id="01" size="lg"/><div><h3>{patient.name}</h3><p>{patient.age} years · Female</p><code>{patient.id}</code></div><div className="privacy-lock"><LockKeyhole /><small>Medical history stays hidden until Priya authorizes this consultation.</small></div><button className="button dark" onClick={()=>navigate('/doctor/consultations/authorize')}>Request consultation access<ArrowRight /></button></div>}</section><section className="dashboard-side"><div className="paper stat-card"><span>Draft prescriptions</span><strong>1</strong><small>Last edited yesterday</small></div><div className="recent-card"><h3>Recent patients</h3>{['Priya Desai','Rahul Kulkarni','Sneha Iyer'].map((name,index)=><div key={name}><span className="mini-initial">{name.split(' ').map(x=>x[0]).join('')}</span><strong>{name}</strong><small>{28-index} Apr 2025</small></div>)}</div></section></main></AppShell>}

export function AuthorizationPage(){const navigate=useNavigate();const {setAuthorized}=useAppState();const [approved,setApproved]=useState(false);const [code,setCode]=useState(['','','','','','']);const valid=code.join('')==='482169';return <AppShell role="doctor"><PortalHeader eyebrow="Consultations · Authorization" title="Authorize this consultation"/><main className="authorization-layout"><section><div className="patient-banner"><PortraitAvatar id="01" size="lg"/><div><h2>{patient.name}</h2><p>34 · Female</p><code>{patient.id}</code></div><span>{doctor.clinic}<small>Consultation today</small></span></div><ol className="auth-rail"><li className="done"><Check/>Request sent</li><li className={approved?'done':'active'}>{approved?<Check/>:2}Patient approved</li><li className={approved?'active':''}>3 Enter code</li><li>4 Access granted</li></ol><div className="authorization-card">{!approved?<><ShieldCheck size={46}/><h2>Waiting for Priya</h2><p>For the demo, open the patient request and approve this consultation.</p><button className="button primary" onClick={()=>setApproved(true)}>Simulate patient approval<ArrowRight /></button></>:<><span className="status-pill"><CheckCircle2/>Patient approved</span><h2>Enter Priya’s single-use code</h2><p>The patient sees <strong className="mono">482169</strong> in her MedPal account.</p><div className="otp-row">{code.map((digit,index)=><input key={index} value={digit} maxLength={1} onChange={event=>{const next=[...code];next[index]=event.target.value;setCode(next)}}/>)}</div><div className="code-meta"><span><Clock3/>04:37 remaining</span><span>3 attempts remaining</span></div><button disabled={!valid} className="button primary wide" onClick={()=>{setAuthorized(true);navigate('/doctor/consultations/priya')}}>Verify code & open consultation<ArrowRight /></button></>}</div></section><aside className="paper scope-card"><h2>Your access is scoped</h2><p>You will only have access to:</p>{[[UserRound,doctor.name,'This doctor'],[UserRound,patient.name,'This patient'],[FileText,'This consultation','Ends when it closes']].map(([Icon,title,copy])=><div className="scope-row" key={String(title)}><Icon/><span><strong>{title as string}</strong><small>{copy as string}</small></span></div>)}<div className="soft-note"><ShieldCheck/><span>Priya’s privacy is protected.<small>No medical history appears before authorization.</small></span></div></aside></main></AppShell>}

function TreatmentConstellation({onSelect}:{onSelect?:(medicine:string)=>void}){return <div className="treatment-map"><div className="map-rings"/><div className="patient-center"><PortraitAvatar id="01" size="lg"/><strong>{patient.name}</strong><small>Your patient today</small></div>{medicines.map((med,index)=><button key={med.name} onClick={()=>onSelect?.(med.name)} className={`treatment-orb ${med.tone} med-${index}`}><strong>{med.name}</strong><b>{med.dose}</b><small>{med.instruction}</small></button>)}</div>}

export function ConsultationPage(){const navigate=useNavigate();return <AppShell role="doctor"><PortalHeader eyebrow="Consultation · Priya Desai" title="Treatment in context"><span className="status-pill"><ShieldCheck/>Authorized · 23 min left</span></PortalHeader><main className="consultation-layout"><section><div className="consultation-patient"><PortraitAvatar id="01" size="lg"/><div><h2>{patient.name}</h2><p>34 · Female · <span className="mono">{patient.id}</span></p><div className="chips"><span>Hypertension</span><span>Type 2 diabetes</span><span>High cholesterol</span></div></div></div><div className="map-card"><div className="section-heading"><div><p className="eyebrow">Treatment constellation</p><h2>Five medicines, one view</h2></div><div className="legend"><span><i className="mint"/>Active</span><span><i className="coral"/>Needs review</span><span><i className="grey"/>Historical</span></div></div><TreatmentConstellation onSelect={(medicine)=>medicine==='Amlodipine'&&navigate('/doctor/consultations/priya/medication/amlodipine')}/></div><div className="history-strip"><div><strong>Previous consultation</strong><small>12 Apr 2025 · Routine follow-up</small></div><div><strong>Prescription history</strong><small>3 prior prescriptions</small></div><div><strong>Clinical notes</strong><small>No known drug allergies</small></div></div></section><aside className="paper draft-panel"><p className="eyebrow ink">Current prescription · Draft</p><h2>{doctor.clinic}</h2>{medicines.slice(0,4).map((med,index)=><button key={med.name} className="draft-med" onClick={()=>index===1&&navigate('/doctor/consultations/priya/medication/amlodipine')}><i className={med.tone}/><span><strong>{med.name} {med.dose}</strong><small>{med.instruction}</small></span><em>{index===1?'Review':'Continue'}</em><ArrowRight/></button>)}<button className="add-med"><Plus/>Add medicine</button><button className="button dark wide" onClick={()=>navigate('/doctor/consultations/priya/review')}>Review changes<ArrowRight/></button></aside></main></AppShell>}

export function MedicationDecisionPage(){const navigate=useNavigate();return <AppShell role="doctor"><PortalHeader eyebrow="Consultation · Medication decision" title="Amlodipine"><span className="attention-pill">Requires attention</span></PortalHeader><main className="decision-wrap"><div className="decision-context"><span>Priya Desai</span><code>{patient.id}</code><span>Hypertension</span></div><section className="paper decision-card"><div className="decision-columns"><article><p className="eyebrow ink">Before</p><h2>5 mg once daily</h2><small>Started 12 Jan 2024</small></article><article><p className="eyebrow ink">Proposed</p><div className="inline-fields"><select defaultValue="10 mg"><option>10 mg</option></select><select defaultValue="once daily"><option>once daily</option></select></div></article><article><p className="eyebrow ink">Reason</p><textarea defaultValue="Blood pressure remains above target; increase dose and review in 4 weeks."/></article></div><div className="decision-actions"><button><Check/>Continue</button><button className="selected"><Edit3/>Change</button><button><X/>Stop</button><button><Plus/>Add</button><button>Not reviewed</button></div><div className="detail-fields"><label>When<select><option>Morning</option></select></label><label>Timing<select><option>After breakfast</option></select></label><label>Duration<select><option>28 days</option></select></label><label>Patient instructions<input defaultValue="Take one tablet daily after breakfast."/></label></div><div className="decision-footer"><div className="demo-disclosure"><Info/><span><strong>Review active medicines before saving.</strong><small>Confirm patient-specific factors and potential duplication.</small></span></div><button className="button dark" onClick={()=>navigate('/doctor/consultations/priya/review')}>Save change<ArrowRight/></button></div></section></main></AppShell>}

const changes=[['Changed','Amlodipine','5 mg → 10 mg once daily','coral'],['Continued','Metformin','500 mg twice daily','mint'],['Added','Vitamin D3','1000 IU once daily','blue'],['Not reviewed','Atorvastatin','10 mg nightly · remains in history','grey']]
export function ReviewIssuePage(){const navigate=useNavigate();const {setIssued}=useAppState();return <AppShell role="doctor"><PortalHeader eyebrow="Consultation · Final review" title="Review before issuing"/><main className="review-layout"><section><div className="review-patient"><PortraitAvatar id="01" size="lg"/><div><h2>{patient.name}</h2><p>34 · Female · <span className="mono">{patient.id}</span></p></div></div><h2 className="section-title">Changes in this prescription</h2>{changes.map(([status,name,detail,tone])=><div className="change-row" key={name}><i className={tone}/><span><small>{status}</small><strong>{name}</strong></span><b>{detail}</b><button>Edit<ArrowRight/></button></div>)}<div className="soft-note"><Info/><span>Corrections after issuing create a linked new version.<small>The issued record itself cannot be silently edited.</small></span></div><div className="issue-actions"><Link className="button ghost" to="/doctor/consultations/priya"><ArrowLeft/>Back to consultation</Link><button className="button primary" onClick={()=>{setIssued(true);navigate('/patient/home')}}>Issue prescription<ArrowRight/></button></div></section><PrescriptionSheet compact/></main></AppShell>}

export function PatientHomePage(){const navigate=useNavigate();return <AppShell role="patient"><PortalHeader eyebrow="Your care · Updated today" title="Good evening, Priya."/><main className="patient-home-layout"><section className="patient-map"><h2>Your treatment today</h2><p>Four medicines · Updated today</p><TreatmentConstellation/></section><section className="paper changed-panel"><p className="eyebrow ink">Issued today · Dr. Arjun Mehta</p><h2>What changed today</h2><p>Here’s what’s new and what stays the same.</p>{changes.map(([status,name,detail,tone])=><div className="patient-change" key={name}><i className={tone}/><span><strong>{status === 'Changed' ? `${name} increased` : status === 'Continued' ? `Keep taking ${name}` : status === 'Added' ? `${name} was added` : `${name} was not reviewed`}</strong><small>{detail}</small></span></div>)}<button className="button primary wide" onClick={()=>navigate('/patient/prescriptions/RX-250428-0187')}>View signed prescription<ArrowRight/></button></section></main></AppShell>}

export function PrescriptionSheet({compact=false}:{compact?:boolean}){return <article className={`prescription-sheet ${compact?'compact':''}`}><header><div><strong>MedPal</strong><small>Care, in context.</small></div><div><b>{doctor.clinic}</b><small>{doctor.address}</small></div></header><div className="rx-meta"><div><strong>{doctor.name}</strong><small>{doctor.qualification}<br/>{doctor.council}<br/>{doctor.registration}</small></div><div><b>Priya Desai</b><small>34 · Female<br/>{patient.id}<br/>28 Apr 2025</small></div></div><h3>Rx</h3><table><thead><tr><th>Medicine</th><th>When</th><th>Instructions</th><th>Duration</th></tr></thead><tbody><tr><td>Metformin<br/><small>500 mg</small></td><td><span className="time-chip"><Sun/>Morning</span><span className="time-chip night"><Moon/>Evening</span></td><td>One tablet with meals</td><td>28 days</td></tr><tr><td>Amlodipine<br/><small>10 mg</small></td><td><span className="time-chip"><Sun/>Morning</span></td><td>One tablet after breakfast</td><td>28 days</td></tr><tr><td>Vitamin D3<br/><small>1000 IU</small></td><td><span className="time-chip"><Sun/>Morning</span></td><td>One tablet after breakfast</td><td>28 days</td></tr></tbody></table><footer><div><b>Follow up</b><small>Review in 4 weeks.</small></div><div className="signature">A. Mehta<small>Digitally issued through MedPal</small></div><div className="verified-seal"><FileCheck2/>MP-8A42</div></footer></article>}

export function PrescriptionPage(){return <AppShell role="patient"><div className="document-toolbar"><Link to="/patient/home"><ArrowLeft/>Back to prescriptions</Link><span>Page 1 of 1</span><div><button><Download/>Download PDF</button><button><Printer/>Print</button></div></div><main className="document-view"><PrescriptionSheet/></main></AppShell>}
